kind: Service
apiVersion: v1
metadata:
  name: author-service
  labels:
    app: author-service
spec:
  selector:
    app: author-service
  ports:
  - protocol: TCP
    port: 50052
    targetPort: 50051
