apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher-service
  labels:
    app: publisher-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: publisher-service
  template:
    metadata:
      labels:
        app: publisher-service
    spec:
      containers:
      - name: publisher-service
        image: quay.io/tkaufler/publisher-service:alpha
        imagePullPolicy: IfNotPresent
        command: [
          "./publisher-service",
          "--selector=static",
          "--server_address=:8880"
        ]
        env:
        - name: DB_HOST
          value: "mongo:27017"
        - name: UPDATED_AT
          value: "Mon 21 May 2018 13:10:45 GMT"
        ports:
        - containerPort: 8880
          name: publisher-port           
