// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/book.proto

package publication_management_book

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category" json:"category,omitempty"`
	Language             string   `protobuf:"bytes,4,opt,name=language" json:"language,omitempty"`
	Pages                int32    `protobuf:"varint,5,opt,name=pages" json:"pages,omitempty"`
	AuthorId             string   `protobuf:"bytes,6,opt,name=author_id,json=authorId" json:"author_id,omitempty"`
	PublisherId          string   `protobuf:"bytes,7,opt,name=publisher_id,json=publisherId" json:"publisher_id,omitempty"`
	Copies               int32    `protobuf:"varint,8,opt,name=copies" json:"copies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_book_67e9d92cc1d86e81, []int{0}
}
func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (dst *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(dst, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Book) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Book) GetPages() int32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Book) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Book) GetPublisherId() string {
	if m != nil {
		return m.PublisherId
	}
	return ""
}

func (m *Book) GetCopies() int32 {
	if m != nil {
		return m.Copies
	}
	return 0
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_book_67e9d92cc1d86e81, []int{1}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Response struct {
	Registered           bool     `protobuf:"varint,1,opt,name=registered" json:"registered,omitempty"`
	Book                 *Book    `protobuf:"bytes,2,opt,name=book" json:"book,omitempty"`
	PublisherId          string   `protobuf:"bytes,3,opt,name=publisher_id,json=publisherId" json:"publisher_id,omitempty"`
	Books                []*Book  `protobuf:"bytes,4,rep,name=books" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_book_67e9d92cc1d86e81, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetRegistered() bool {
	if m != nil {
		return m.Registered
	}
	return false
}

func (m *Response) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func (m *Response) GetPublisherId() string {
	if m != nil {
		return m.PublisherId
	}
	return ""
}

func (m *Response) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*Book)(nil), "publication.management.book.Book")
	proto.RegisterType((*GetRequest)(nil), "publication.management.book.GetRequest")
	proto.RegisterType((*Response)(nil), "publication.management.book.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for BookService service

type BookServiceClient interface {
	PublishBook(ctx context.Context, in *Book, opts ...client.CallOption) (*Response, error)
	GetPublishedBooks(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type bookServiceClient struct {
	c           client.Client
	serviceName string
}

func NewBookServiceClient(serviceName string, c client.Client) BookServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "publication.management.book"
	}
	return &bookServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *bookServiceClient) PublishBook(ctx context.Context, in *Book, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.PublishBook", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetPublishedBooks(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.GetPublishedBooks", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BookService service

type BookServiceHandler interface {
	PublishBook(context.Context, *Book, *Response) error
	GetPublishedBooks(context.Context, *GetRequest, *Response) error
}

func RegisterBookServiceHandler(s server.Server, hdlr BookServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&BookService{hdlr}, opts...))
}

type BookService struct {
	BookServiceHandler
}

func (h *BookService) PublishBook(ctx context.Context, in *Book, out *Response) error {
	return h.BookServiceHandler.PublishBook(ctx, in, out)
}

func (h *BookService) GetPublishedBooks(ctx context.Context, in *GetRequest, out *Response) error {
	return h.BookServiceHandler.GetPublishedBooks(ctx, in, out)
}

func init() { proto.RegisterFile("proto/book.proto", fileDescriptor_book_67e9d92cc1d86e81) }

var fileDescriptor_book_67e9d92cc1d86e81 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcf, 0x4a, 0xfb, 0x40,
	0x10, 0xfe, 0xa5, 0x4d, 0xfa, 0x4b, 0x27, 0x45, 0x74, 0x10, 0x59, 0x5a, 0x90, 0x36, 0x20, 0xf6,
	0x14, 0xa1, 0x22, 0xde, 0xbd, 0x94, 0xde, 0x24, 0x9e, 0x3c, 0xc9, 0x36, 0x19, 0xd2, 0xa5, 0x6d,
	0x36, 0x66, 0x37, 0x82, 0x0f, 0xe7, 0x33, 0x08, 0x3e, 0x91, 0xec, 0x6e, 0x5b, 0x85, 0x42, 0xed,
	0x2d, 0xdf, 0x9f, 0xf9, 0x32, 0xf3, 0x25, 0x70, 0x5a, 0xd5, 0x52, 0xcb, 0x9b, 0xb9, 0x94, 0xcb,
	0xc4, 0x3e, 0xe2, 0xa0, 0x6a, 0xe6, 0x2b, 0x91, 0x71, 0x2d, 0x64, 0x99, 0xac, 0x79, 0xc9, 0x0b,
	0x5a, 0x53, 0xa9, 0x13, 0x63, 0x89, 0xbf, 0x3c, 0xf0, 0x1f, 0xa4, 0x5c, 0xe2, 0x09, 0xb4, 0x44,
	0xce, 0xbc, 0xa1, 0x37, 0xee, 0xa6, 0x2d, 0x91, 0xe3, 0x39, 0x04, 0x5a, 0xe8, 0x15, 0xb1, 0x96,
	0xa5, 0x1c, 0xc0, 0x3e, 0x84, 0x19, 0xd7, 0x54, 0xc8, 0xfa, 0x9d, 0xb5, 0xad, 0xb0, 0xc3, 0x46,
	0x5b, 0xf1, 0xb2, 0x68, 0x78, 0x41, 0xcc, 0x77, 0xda, 0x16, 0x9b, 0xb4, 0x8a, 0x17, 0xa4, 0x58,
	0x30, 0xf4, 0xc6, 0x41, 0xea, 0x00, 0x0e, 0xa0, 0xcb, 0x1b, 0xbd, 0x90, 0xf5, 0x8b, 0xc8, 0x59,
	0xc7, 0x8d, 0x38, 0x62, 0x96, 0xe3, 0x08, 0x7a, 0x76, 0x71, 0xb5, 0x20, 0xab, 0xff, 0xb7, 0x7a,
	0xb4, 0xe3, 0x66, 0x39, 0x5e, 0x40, 0x27, 0x93, 0x95, 0x20, 0xc5, 0x42, 0x1b, 0xbb, 0x41, 0x71,
	0x0f, 0x60, 0x4a, 0x3a, 0xa5, 0xd7, 0x86, 0x94, 0x8e, 0x3f, 0x3c, 0x08, 0x53, 0x52, 0x95, 0x2c,
	0x15, 0xe1, 0x25, 0x40, 0x4d, 0x85, 0x50, 0x9a, 0x6a, 0x72, 0xe7, 0x86, 0xe9, 0x2f, 0x06, 0xef,
	0xc0, 0x37, 0xbd, 0xd8, 0xab, 0xa3, 0xc9, 0x28, 0x39, 0xd0, 0x5d, 0x62, 0x7a, 0x4b, 0xad, 0x7d,
	0x6f, 0xd9, 0xf6, 0xfe, 0xb2, 0xf7, 0x10, 0x18, 0xab, 0x62, 0xfe, 0xb0, 0x7d, 0x5c, 0xb4, 0xf3,
	0x4f, 0x3e, 0x3d, 0x88, 0x0c, 0x7e, 0xa2, 0xfa, 0x4d, 0x64, 0x84, 0xcf, 0x10, 0x3d, 0xba, 0x5c,
	0xfb, 0xe1, 0xfe, 0x0e, 0xea, 0x5f, 0x1d, 0xb4, 0x6c, 0xbb, 0x89, 0xff, 0x21, 0xc1, 0xd9, 0x94,
	0xf4, 0x26, 0x9d, 0x72, 0x33, 0xac, 0xf0, 0xfa, 0xe0, 0xf4, 0x4f, 0xd1, 0x47, 0xbf, 0x66, 0xde,
	0xb1, 0x3f, 0xe6, 0xed, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xf4, 0x4e, 0x90, 0xac, 0x02,
	0x00, 0x00,
}
