// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/publisher.proto

package publication_manager_publisher

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Publisher struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Country              string          `protobuf:"bytes,3,opt,name=country" json:"country,omitempty"`
	Language             string          `protobuf:"bytes,4,opt,name=language" json:"language,omitempty"`
	Category             map[string]bool `protobuf:"bytes,5,rep,name=category" json:"category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Capacity             int32           `protobuf:"varint,6,opt,name=capacity" json:"capacity,omitempty"`
	Commitment           int32           `protobuf:"varint,7,opt,name=commitment" json:"commitment,omitempty"`
	Created              bool            `protobuf:"varint,8,opt,name=created" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Publisher) Reset()         { *m = Publisher{} }
func (m *Publisher) String() string { return proto.CompactTextString(m) }
func (*Publisher) ProtoMessage()    {}
func (*Publisher) Descriptor() ([]byte, []int) {
	return fileDescriptor_publisher_7f5f943fdaca6ce9, []int{0}
}
func (m *Publisher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Publisher.Unmarshal(m, b)
}
func (m *Publisher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Publisher.Marshal(b, m, deterministic)
}
func (dst *Publisher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Publisher.Merge(dst, src)
}
func (m *Publisher) XXX_Size() int {
	return xxx_messageInfo_Publisher.Size(m)
}
func (m *Publisher) XXX_DiscardUnknown() {
	xxx_messageInfo_Publisher.DiscardUnknown(m)
}

var xxx_messageInfo_Publisher proto.InternalMessageInfo

func (m *Publisher) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Publisher) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Publisher) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Publisher) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Publisher) GetCategory() map[string]bool {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Publisher) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Publisher) GetCommitment() int32 {
	if m != nil {
		return m.Commitment
	}
	return 0
}

func (m *Publisher) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

type Requirement struct {
	Language             string   `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=category" json:"category,omitempty"`
	Copies               int32    `protobuf:"varint,3,opt,name=copies" json:"copies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Requirement) Reset()         { *m = Requirement{} }
func (m *Requirement) String() string { return proto.CompactTextString(m) }
func (*Requirement) ProtoMessage()    {}
func (*Requirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_publisher_7f5f943fdaca6ce9, []int{1}
}
func (m *Requirement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requirement.Unmarshal(m, b)
}
func (m *Requirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requirement.Marshal(b, m, deterministic)
}
func (dst *Requirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requirement.Merge(dst, src)
}
func (m *Requirement) XXX_Size() int {
	return xxx_messageInfo_Requirement.Size(m)
}
func (m *Requirement) XXX_DiscardUnknown() {
	xxx_messageInfo_Requirement.DiscardUnknown(m)
}

var xxx_messageInfo_Requirement proto.InternalMessageInfo

func (m *Requirement) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Requirement) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Requirement) GetCopies() int32 {
	if m != nil {
		return m.Copies
	}
	return 0
}

type Response struct {
	Publisher            *Publisher `protobuf:"bytes,1,opt,name=publisher" json:"publisher,omitempty"`
	Availability         bool       `protobuf:"varint,2,opt,name=availability" json:"availability,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_publisher_7f5f943fdaca6ce9, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetPublisher() *Publisher {
	if m != nil {
		return m.Publisher
	}
	return nil
}

func (m *Response) GetAvailability() bool {
	if m != nil {
		return m.Availability
	}
	return false
}

func init() {
	proto.RegisterType((*Publisher)(nil), "publication.manager.publisher.Publisher")
	proto.RegisterMapType((map[string]bool)(nil), "publication.manager.publisher.Publisher.CategoryEntry")
	proto.RegisterType((*Requirement)(nil), "publication.manager.publisher.Requirement")
	proto.RegisterType((*Response)(nil), "publication.manager.publisher.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PublisherService service

type PublisherServiceClient interface {
	FindAvailable(ctx context.Context, in *Requirement, opts ...client.CallOption) (*Response, error)
	CreatePublisher(ctx context.Context, in *Publisher, opts ...client.CallOption) (*Response, error)
}

type publisherServiceClient struct {
	c           client.Client
	serviceName string
}

func NewPublisherServiceClient(serviceName string, c client.Client) PublisherServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "publication.manager.publisher"
	}
	return &publisherServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *publisherServiceClient) FindAvailable(ctx context.Context, in *Requirement, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PublisherService.FindAvailable", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherServiceClient) CreatePublisher(ctx context.Context, in *Publisher, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "PublisherService.CreatePublisher", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PublisherService service

type PublisherServiceHandler interface {
	FindAvailable(context.Context, *Requirement, *Response) error
	CreatePublisher(context.Context, *Publisher, *Response) error
}

func RegisterPublisherServiceHandler(s server.Server, hdlr PublisherServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&PublisherService{hdlr}, opts...))
}

type PublisherService struct {
	PublisherServiceHandler
}

func (h *PublisherService) FindAvailable(ctx context.Context, in *Requirement, out *Response) error {
	return h.PublisherServiceHandler.FindAvailable(ctx, in, out)
}

func (h *PublisherService) CreatePublisher(ctx context.Context, in *Publisher, out *Response) error {
	return h.PublisherServiceHandler.CreatePublisher(ctx, in, out)
}

func init() { proto.RegisterFile("proto/publisher.proto", fileDescriptor_publisher_7f5f943fdaca6ce9) }

var fileDescriptor_publisher_7f5f943fdaca6ce9 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0xae, 0x93, 0x40,
	0x14, 0xc6, 0x85, 0x5e, 0x7a, 0xe9, 0xa9, 0x57, 0x6f, 0x26, 0x6a, 0x26, 0x24, 0x1a, 0xc2, 0x46,
	0xe2, 0x02, 0x93, 0x9a, 0x18, 0xa3, 0x2b, 0xd3, 0xd8, 0xb5, 0x19, 0xd7, 0x2e, 0xa6, 0xc3, 0x29,
	0x4e, 0x84, 0x19, 0x84, 0x81, 0x84, 0x77, 0xf4, 0x29, 0x7c, 0x12, 0xc3, 0x50, 0x28, 0x75, 0x61,
	0x7b, 0x77, 0xf3, 0x9d, 0x3f, 0xf3, 0xcd, 0xf7, 0x6b, 0x81, 0xe7, 0x65, 0xa5, 0x8d, 0x7e, 0x5b,
	0x36, 0xfb, 0x5c, 0xd6, 0x3f, 0xb0, 0x4a, 0xac, 0x26, 0x2f, 0x6d, 0x41, 0x70, 0x23, 0xb5, 0x4a,
	0x0a, 0xae, 0x78, 0xd6, 0xb7, 0xc6, 0xa1, 0xe8, 0xb7, 0x0b, 0xab, 0xaf, 0xa3, 0x22, 0x4f, 0xc0,
	0x95, 0x29, 0x75, 0x42, 0x27, 0x5e, 0x31, 0x57, 0xa6, 0x84, 0xc0, 0x8d, 0xe2, 0x05, 0x52, 0xd7,
	0x56, 0xec, 0x99, 0x50, 0xb8, 0x15, 0xba, 0x51, 0xa6, 0xea, 0xe8, 0xc2, 0x96, 0x47, 0x49, 0x02,
	0xf0, 0x73, 0xae, 0xb2, 0x86, 0x67, 0x48, 0x6f, 0x6c, 0x6b, 0xd2, 0x84, 0x81, 0x2f, 0xb8, 0xc1,
	0x4c, 0x57, 0x1d, 0xf5, 0xc2, 0x45, 0xbc, 0xde, 0xbc, 0x4f, 0xfe, 0xfb, 0xb2, 0x64, 0x7a, 0x55,
	0xb2, 0x3d, 0x2e, 0x7e, 0xe9, 0x5d, 0xd8, 0x74, 0x4f, 0xef, 0x27, 0x78, 0xc9, 0x85, 0x34, 0x1d,
	0x5d, 0x86, 0x4e, 0xec, 0xb1, 0x49, 0x93, 0x57, 0x00, 0x42, 0x17, 0x85, 0x34, 0x05, 0x2a, 0x43,
	0x6f, 0x6d, 0x77, 0x56, 0xb1, 0x29, 0x2a, 0xe4, 0x06, 0x53, 0xea, 0x87, 0x4e, 0xec, 0xb3, 0x51,
	0x06, 0x9f, 0xe0, 0xee, 0xcc, 0x90, 0xdc, 0xc3, 0xe2, 0x27, 0x76, 0x47, 0x2a, 0xfd, 0x91, 0x3c,
	0x03, 0xaf, 0xe5, 0x79, 0x33, 0x70, 0xf1, 0xd9, 0x20, 0x3e, 0xba, 0x1f, 0x9c, 0xe8, 0x3b, 0xac,
	0x19, 0xfe, 0x6a, 0x64, 0x85, 0xd6, 0x65, 0x4e, 0xc4, 0xf9, 0x87, 0x48, 0x30, 0x23, 0x32, 0xf0,
	0x3d, 0x25, 0x7b, 0x01, 0x4b, 0xa1, 0x4b, 0x89, 0xb5, 0x45, 0xec, 0xb1, 0xa3, 0x8a, 0x5a, 0xf0,
	0x19, 0xd6, 0xa5, 0x56, 0x35, 0x92, 0x1d, 0xac, 0x26, 0x58, 0xf6, 0xf2, 0xf5, 0x26, 0xbe, 0x16,
	0x29, 0x3b, 0xad, 0x92, 0x08, 0x1e, 0xf3, 0x96, 0xcb, 0x9c, 0xef, 0x65, 0xde, 0x93, 0x1c, 0x32,
	0x9d, 0xd5, 0x36, 0x7f, 0x1c, 0xb8, 0x9f, 0x96, 0xbf, 0x61, 0xd5, 0x4a, 0x81, 0xe4, 0x00, 0x77,
	0x3b, 0xa9, 0xd2, 0xcf, 0xc3, 0x60, 0x8e, 0xe4, 0xcd, 0x05, 0xfb, 0x19, 0x99, 0xe0, 0xf5, 0xc5,
	0xd9, 0x21, 0x66, 0xf4, 0x88, 0x1c, 0xe0, 0xe9, 0xd6, 0xfe, 0x36, 0xa7, 0xff, 0xe9, 0xd5, 0x41,
	0x1f, 0xe0, 0xb3, 0x5f, 0xda, 0x0f, 0xe6, 0xdd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x23,
	0xf2, 0x55, 0x49, 0x03, 0x00, 0x00,
}
