// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/author.proto

package publication_management_author

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Author struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=country" json:"country,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,7,opt,name=password" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,8,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_author_58586053224bd097, []int{0}
}
func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (dst *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(dst, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Author) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Author) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Author) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Author) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Author) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Author) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Author) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_author_58586053224bd097, []int{1}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type GetAllRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_author_58586053224bd097, []int{2}
}
func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (dst *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(dst, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

type Response struct {
	Created              bool      `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Author               *Author   `protobuf:"bytes,2,opt,name=author" json:"author,omitempty"`
	Authors              []*Author `protobuf:"bytes,3,rep,name=authors" json:"authors,omitempty"`
	Errors               []*Error  `protobuf:"bytes,4,rep,name=errors" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_author_58586053224bd097, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Response) GetAuthors() []*Author {
	if m != nil {
		return m.Authors
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_author_58586053224bd097, []int{4}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Author)(nil), "publication.management.author.Author")
	proto.RegisterType((*Token)(nil), "publication.management.author.Token")
	proto.RegisterType((*GetAllRequest)(nil), "publication.management.author.GetAllRequest")
	proto.RegisterType((*Response)(nil), "publication.management.author.Response")
	proto.RegisterType((*Error)(nil), "publication.management.author.Error")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AuthorService service

type AuthorServiceClient interface {
	CreateAuthor(ctx context.Context, in *Author, opts ...client.CallOption) (*Response, error)
	GetAuthor(ctx context.Context, in *Author, opts ...client.CallOption) (*Response, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...client.CallOption) (*Response, error)
	ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error)
	Authenticate(ctx context.Context, in *Author, opts ...client.CallOption) (*Token, error)
}

type authorServiceClient struct {
	c           client.Client
	serviceName string
}

func NewAuthorServiceClient(serviceName string, c client.Client) AuthorServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "publication.management.author"
	}
	return &authorServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *authorServiceClient) CreateAuthor(ctx context.Context, in *Author, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthorService.CreateAuthor", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorServiceClient) GetAuthor(ctx context.Context, in *Author, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthorService.GetAuthor", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorServiceClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthorService.GetAll", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorServiceClient) ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.serviceName, "AuthorService.ValidateToken", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorServiceClient) Authenticate(ctx context.Context, in *Author, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.serviceName, "AuthorService.Authenticate", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthorService service

type AuthorServiceHandler interface {
	CreateAuthor(context.Context, *Author, *Response) error
	GetAuthor(context.Context, *Author, *Response) error
	GetAll(context.Context, *GetAllRequest, *Response) error
	ValidateToken(context.Context, *Token, *Token) error
	Authenticate(context.Context, *Author, *Token) error
}

func RegisterAuthorServiceHandler(s server.Server, hdlr AuthorServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&AuthorService{hdlr}, opts...))
}

type AuthorService struct {
	AuthorServiceHandler
}

func (h *AuthorService) CreateAuthor(ctx context.Context, in *Author, out *Response) error {
	return h.AuthorServiceHandler.CreateAuthor(ctx, in, out)
}

func (h *AuthorService) GetAuthor(ctx context.Context, in *Author, out *Response) error {
	return h.AuthorServiceHandler.GetAuthor(ctx, in, out)
}

func (h *AuthorService) GetAll(ctx context.Context, in *GetAllRequest, out *Response) error {
	return h.AuthorServiceHandler.GetAll(ctx, in, out)
}

func (h *AuthorService) ValidateToken(ctx context.Context, in *Token, out *Token) error {
	return h.AuthorServiceHandler.ValidateToken(ctx, in, out)
}

func (h *AuthorService) Authenticate(ctx context.Context, in *Author, out *Token) error {
	return h.AuthorServiceHandler.Authenticate(ctx, in, out)
}

func init() { proto.RegisterFile("proto/author.proto", fileDescriptor_author_58586053224bd097) }

var fileDescriptor_author_58586053224bd097 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x8a, 0xd4, 0x40,
	0x10, 0x35, 0x33, 0x93, 0x4c, 0xa6, 0x66, 0x47, 0xa1, 0xf0, 0xd0, 0x8c, 0x2c, 0x0c, 0x41, 0x71,
	0x0f, 0x12, 0x61, 0xbc, 0xba, 0xc8, 0x22, 0xe2, 0xcd, 0x43, 0x14, 0x6f, 0xa2, 0xbd, 0x49, 0xa9,
	0x8d, 0x49, 0x3a, 0xdb, 0xdd, 0xb3, 0xe2, 0x5f, 0xfa, 0x0d, 0xfe, 0x81, 0x7f, 0x20, 0x5d, 0x9d,
	0xe0, 0x78, 0x31, 0x51, 0xd8, 0x5b, 0xbd, 0x7a, 0xf5, 0x2a, 0xfd, 0xaa, 0x8a, 0x00, 0x76, 0x46,
	0x3b, 0xfd, 0x58, 0x1e, 0xdc, 0x67, 0x6d, 0x72, 0x06, 0x78, 0xda, 0x1d, 0x2e, 0x6b, 0x55, 0x4a,
	0xa7, 0x74, 0x9b, 0x37, 0xb2, 0x95, 0x9f, 0xa8, 0xa1, 0xd6, 0xe5, 0xa1, 0x28, 0xfb, 0x1e, 0x41,
	0x72, 0xc1, 0x21, 0xde, 0x86, 0x99, 0xaa, 0x44, 0xb4, 0x8b, 0xce, 0x56, 0xc5, 0x4c, 0x55, 0x78,
	0x0a, 0xf0, 0x51, 0x19, 0xeb, 0xde, 0xb7, 0xb2, 0x21, 0x31, 0xe3, 0xfc, 0x8a, 0x33, 0xaf, 0x64,
	0x43, 0x78, 0x0f, 0x56, 0xb5, 0x1c, 0xd8, 0x39, 0xb3, 0xa9, 0x4f, 0x30, 0x29, 0x60, 0x29, 0xab,
	0xca, 0x90, 0xb5, 0x62, 0xc1, 0xd4, 0x00, 0x3d, 0x53, 0xea, 0x43, 0xeb, 0xcc, 0x37, 0x11, 0x07,
	0xa6, 0x87, 0x78, 0x17, 0x62, 0x6a, 0xa4, 0xaa, 0x45, 0xc2, 0xf9, 0x00, 0x70, 0x0b, 0x69, 0x27,
	0xad, 0xfd, 0xaa, 0x4d, 0x25, 0x96, 0xe1, 0x2b, 0x03, 0xf6, 0x0a, 0xa7, 0xbf, 0x50, 0x2b, 0xd2,
	0xa0, 0x60, 0x90, 0x5d, 0x41, 0xfc, 0xc6, 0x07, 0xbf, 0xe9, 0xe8, 0x88, 0xf6, 0xd9, 0x6b, 0x59,
	0xab, 0x8a, 0x1d, 0xa5, 0x45, 0x00, 0xf8, 0x14, 0x12, 0x32, 0x46, 0x1b, 0x2b, 0xe6, 0xbb, 0xf9,
	0xd9, 0x7a, 0x7f, 0x3f, 0xff, 0xeb, 0xdc, 0xf2, 0x17, 0xbe, 0xb8, 0xe8, 0x35, 0xd9, 0x1d, 0xd8,
	0xbc, 0x24, 0x77, 0x51, 0xd7, 0x05, 0x5d, 0x1d, 0xc8, 0xba, 0xec, 0x47, 0x04, 0x69, 0x41, 0xb6,
	0xd3, 0xad, 0xe5, 0x61, 0x94, 0x86, 0xa4, 0xa3, 0x30, 0xdd, 0xb4, 0x18, 0x20, 0x9e, 0x43, 0x12,
	0xfa, 0xf1, 0x63, 0xd6, 0xfb, 0x07, 0x23, 0x5f, 0x0d, 0x9b, 0x2a, 0x7a, 0x11, 0x3e, 0x83, 0x65,
	0x88, 0x86, 0x57, 0x4f, 0xd4, 0x0f, 0xaa, 0x23, 0xd7, 0x8b, 0xff, 0x70, 0x7d, 0x0e, 0x31, 0x27,
	0x10, 0x61, 0x51, 0xea, 0x8a, 0xd8, 0x5d, 0x5c, 0x70, 0x8c, 0x3b, 0x58, 0x57, 0x64, 0x4b, 0xa3,
	0x3a, 0xdf, 0xab, 0x3f, 0x9f, 0xe3, 0xd4, 0xfe, 0xe7, 0x1c, 0x36, 0xe1, 0x41, 0xaf, 0xc9, 0x5c,
	0xab, 0x92, 0xf0, 0x03, 0x9c, 0x3c, 0xe7, 0xc9, 0xf4, 0x17, 0x39, 0xcd, 0xce, 0xf6, 0xe1, 0x48,
	0xd9, 0xb0, 0x88, 0xec, 0x16, 0xbe, 0x83, 0x95, 0x5f, 0xd4, 0x4d, 0xb5, 0x97, 0x90, 0x84, 0x3b,
	0xc0, 0x47, 0x23, 0xa2, 0x3f, 0xce, 0xe5, 0xdf, 0x1c, 0x6c, 0xde, 0xfa, 0x8b, 0x95, 0x8e, 0xc2,
	0x95, 0x8f, 0xed, 0x8c, 0xab, 0xb6, 0x93, 0xaa, 0xb8, 0xfd, 0x89, 0xb7, 0x4d, 0xad, 0xf3, 0xb5,
	0x34, 0x75, 0x46, 0x13, 0xdb, 0x5f, 0x26, 0xfc, 0x53, 0x7a, 0xf2, 0x2b, 0x00, 0x00, 0xff, 0xff,
	0x02, 0xb7, 0xe4, 0xdd, 0xaa, 0x04, 0x00, 0x00,
}
