// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/author.proto

package publication_management_author

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Author struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	Books                []*Book  `protobuf:"bytes,5,rep,name=books" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_author_7e98c6d4126599cc, []int{0}
}
func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (dst *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(dst, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Author) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Author) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Author) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Author) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type Book struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	AuthorId             string   `protobuf:"bytes,2,opt,name=author_id,json=authorId" json:"author_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=category" json:"category,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=language" json:"language,omitempty"`
	Pages                int32    `protobuf:"varint,6,opt,name=pages" json:"pages,omitempty"`
	PublisherId          string   `protobuf:"bytes,7,opt,name=publisher_id,json=publisherId" json:"publisher_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_author_7e98c6d4126599cc, []int{1}
}
func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (dst *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(dst, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Book) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Book) GetPages() int32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Book) GetPublisherId() string {
	if m != nil {
		return m.PublisherId
	}
	return ""
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_author_7e98c6d4126599cc, []int{2}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Response struct {
	Created              bool      `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Author               *Author   `protobuf:"bytes,2,opt,name=author" json:"author,omitempty"`
	Authors              []*Author `protobuf:"bytes,3,rep,name=authors" json:"authors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_author_7e98c6d4126599cc, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetAuthor() *Author {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Response) GetAuthors() []*Author {
	if m != nil {
		return m.Authors
	}
	return nil
}

func init() {
	proto.RegisterType((*Author)(nil), "publication.management.author.Author")
	proto.RegisterType((*Book)(nil), "publication.management.author.Book")
	proto.RegisterType((*GetRequest)(nil), "publication.management.author.GetRequest")
	proto.RegisterType((*Response)(nil), "publication.management.author.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AuthorService service

type AuthorServiceClient interface {
	CreateAuthor(ctx context.Context, in *Author, opts ...client.CallOption) (*Response, error)
	GetAuthors(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type authorServiceClient struct {
	c           client.Client
	serviceName string
}

func NewAuthorServiceClient(serviceName string, c client.Client) AuthorServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "publication.management.author"
	}
	return &authorServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *authorServiceClient) CreateAuthor(ctx context.Context, in *Author, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthorService.CreateAuthor", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorServiceClient) GetAuthors(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "AuthorService.GetAuthors", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthorService service

type AuthorServiceHandler interface {
	CreateAuthor(context.Context, *Author, *Response) error
	GetAuthors(context.Context, *GetRequest, *Response) error
}

func RegisterAuthorServiceHandler(s server.Server, hdlr AuthorServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&AuthorService{hdlr}, opts...))
}

type AuthorService struct {
	AuthorServiceHandler
}

func (h *AuthorService) CreateAuthor(ctx context.Context, in *Author, out *Response) error {
	return h.AuthorServiceHandler.CreateAuthor(ctx, in, out)
}

func (h *AuthorService) GetAuthors(ctx context.Context, in *GetRequest, out *Response) error {
	return h.AuthorServiceHandler.GetAuthors(ctx, in, out)
}

func init() { proto.RegisterFile("proto/author.proto", fileDescriptor_author_7e98c6d4126599cc) }

var fileDescriptor_author_7e98c6d4126599cc = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xb1, 0x8e, 0x9b, 0x40,
	0x14, 0x0c, 0xb6, 0xc1, 0xf0, 0xec, 0xa4, 0x58, 0xa5, 0x58, 0xd9, 0xb2, 0xe4, 0x10, 0x45, 0x71,
	0x1a, 0x22, 0x39, 0x55, 0x8a, 0x28, 0x4a, 0x52, 0x44, 0x6e, 0x52, 0x90, 0x0f, 0x70, 0x16, 0x78,
	0xc1, 0x2b, 0x03, 0x4b, 0xd8, 0x25, 0xd2, 0xfd, 0xcf, 0x35, 0xf7, 0x0b, 0xf7, 0x1f, 0xf7, 0x3f,
	0x27, 0xde, 0x82, 0xaf, 0x38, 0xe9, 0xec, 0xeb, 0x76, 0xe6, 0xbd, 0x59, 0x66, 0x06, 0x00, 0x56,
	0x37, 0xca, 0xa8, 0x8f, 0xa2, 0x35, 0x07, 0xd5, 0x44, 0x04, 0xd8, 0xaa, 0x6e, 0x93, 0x42, 0xa6,
	0xc2, 0x48, 0x55, 0x45, 0xa5, 0xa8, 0x44, 0x8e, 0x25, 0x56, 0x26, 0xb2, 0x4b, 0xe1, 0x8d, 0x03,
	0xde, 0x37, 0x3a, 0xb2, 0x57, 0x30, 0x92, 0x19, 0x77, 0xd6, 0xce, 0x26, 0x88, 0x47, 0x32, 0x63,
	0x2b, 0x80, 0xbf, 0xb2, 0xd1, 0x66, 0x5f, 0x89, 0x12, 0xf9, 0x88, 0xf8, 0x80, 0x98, 0x5f, 0xa2,
	0x44, 0xb6, 0x84, 0xa0, 0x10, 0xc3, 0x74, 0x4c, 0x53, 0xbf, 0x23, 0x68, 0xc8, 0x61, 0x2a, 0xb2,
	0xac, 0x41, 0xad, 0xf9, 0x84, 0x46, 0x03, 0x64, 0x9f, 0xc1, 0x4d, 0x94, 0x3a, 0x6a, 0xee, 0xae,
	0xc7, 0x9b, 0xd9, 0xf6, 0x6d, 0xf4, 0xa4, 0xbf, 0xe8, 0xbb, 0x52, 0xc7, 0xd8, 0x2a, 0xc2, 0x5b,
	0x07, 0x26, 0x1d, 0x7e, 0xe4, 0x74, 0x09, 0x81, 0x5d, 0xdf, 0xcb, 0xac, 0x37, 0xea, 0x5b, 0x62,
	0x97, 0xb1, 0xd7, 0xe0, 0x1a, 0x69, 0x8a, 0xc1, 0xa3, 0x05, 0x6c, 0x01, 0x7e, 0x2a, 0x0c, 0xe6,
	0xaa, 0xb9, 0xea, 0x1d, 0x9e, 0x70, 0x37, 0x2b, 0x44, 0x95, 0xb7, 0x22, 0x47, 0xee, 0x0e, 0xc1,
	0x2c, 0xee, 0x6e, 0xab, 0x45, 0x8e, 0x9a, 0x7b, 0x6b, 0x67, 0xe3, 0xc6, 0x16, 0xb0, 0x37, 0x30,
	0xa7, 0x18, 0xfa, 0x80, 0xe4, 0x61, 0x4a, 0xaa, 0xd9, 0x89, 0xdb, 0x65, 0xe1, 0x1c, 0xe0, 0x27,
	0x9a, 0x18, 0xff, 0xb5, 0xa8, 0x4d, 0x78, 0xed, 0x80, 0x1f, 0xa3, 0xae, 0x55, 0xa5, 0xa9, 0xac,
	0xb4, 0x41, 0x61, 0xd0, 0x66, 0xf2, 0xe3, 0x01, 0xb2, 0x2f, 0xe0, 0xd9, 0x1c, 0x94, 0x6a, 0xb6,
	0x7d, 0x77, 0xa6, 0x2d, 0xfb, 0x26, 0xe3, 0x5e, 0xc4, 0xbe, 0xc2, 0xd4, 0x9e, 0x34, 0x1f, 0x53,
	0xdb, 0x17, 0xea, 0x07, 0xd5, 0xf6, 0xce, 0x81, 0x97, 0x96, 0xfb, 0x8d, 0xcd, 0x7f, 0x99, 0x22,
	0xfb, 0x03, 0xf3, 0x1f, 0x64, 0xae, 0xff, 0x68, 0x2e, 0xbb, 0x71, 0xf1, 0xfe, 0xcc, 0xda, 0xd0,
	0x45, 0xf8, 0x82, 0x25, 0x54, 0x94, 0xd5, 0x69, 0xf6, 0xe1, 0x8c, 0xf0, 0xa1, 0xd3, 0x67, 0x3c,
	0x23, 0xf1, 0xe8, 0xdf, 0xf8, 0x74, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x75, 0x89, 0x3a, 0x31,
	0x03, 0x00, 0x00,
}
